export const ENDPOINTS = {
  HEALTH: "/health",
  SESSION_STATE: "/session/state",
  SESSION_RESET: "/session/reset",
  SQL_START: "/sql/start",
  CHARTS_HISTOGRAM: "/charts/histogram",
  CHARTS_OVERVIEW: "/charts/overview",
  CLEANING_AUDIT: "/cleaning/audit",
  VARIABLE_SELECTION: "/variables/selection",
  PIPELINE_TRIGGER: "/pipeline/trigger",
  PIPELINE_RUN: "/pipeline/run",
  ANOMALY_DETECTION_ZSCORE: "/ml/anomaly/zscore",
  ANOMALY_DETECTION_ISOLATION_FOREST: "/ml/anomaly/isolation-forest",
  ANOMALY_DETECTION_KMEANS: "/ml/anomaly/kmeans",
  PREDICTION_REGRESSION: "/ml/prediction/regression",
  PREDICTION_MOVING_AVERAGE: "/ml/prediction/moving-average",
};
