export const chartCatalog = [
  {
    id: "histogram",
    title: "Histogram",
    purpose: "Shows the distribution of a numeric variable.",
    whenToUse: "Use when you want to understand spread, frequency, and concentration of values.",
    recommended: true,
    recommendationReason: "Recommended because metric_value is numeric and suitable for distribution analysis.",
    endpoint: "/charts/histogram",
  },
  {
    id: "bar-category",
    title: "Category Bar Chart",
    purpose: "Compares counts across categories.",
    whenToUse: "Use when you want to compare frequency across discrete groups.",
    recommended: true,
    recommendationReason: "Recommended because category is available as a grouping field.",
    endpoint: "/charts/bar-category",
  },
  {
    id: "boxplot",
    title: "Box Plot",
    purpose: "Summarizes distribution and highlights potential outliers.",
    whenToUse: "Use when you want a compact summary of spread and unusual values.",
    recommended: true,
    recommendationReason: "Recommended because metric_value is numeric and suitable for distribution summary.",
    endpoint: "/charts/boxplot",
  },
  {
    id: "scatter",
    title: "Scatter Plot",
    purpose: "Shows the relationship between two numeric variables.",
    whenToUse: "Use when you want to inspect correlation or patterns between numeric variables.",
    recommended: true,
    recommendationReason: "Recommended because metric_value and secondary_metric can be compared directly.",
    endpoint: "/charts/scatter",
  },
  {
    id: "grouped-comparison",
    title: "Grouped Comparison Chart",
    purpose: "Compares average metric values across categories.",
    whenToUse: "Use when you want to compare aggregated numeric values by group.",
    recommended: true,
    recommendationReason: "Recommended because category can be used to group metric_value.",
    endpoint: "/charts/grouped-comparison",
  },
];